### ISSUE TITLE
am i doing something wrong or

### ISSUE THREAD

**Issue by I3eanoss** [apollyon600/ProjectAlpha#3]
i got the project alpha bot to check my stats and net worth overtime
some issue i faced was the bot wouldn’t take any minecraft ign saying “it never logged onto hypixel” 
i tried with other names and it gave me the same issue
is there something i’m doing wrong or is there an issue

**Comment by BattleB0t** [comment]
Same for me i think the bot is in a very early alpha and it cant do anything

**Comment by johnaqu1no** [comment]
Issue was resolved, this was because of the api key being invalid.
I also abandoned this project long ago so that is why it took this long
